# Google App Engine Configuration for BuildBuzz API
runtime: python311

# The command to start our FastAPI application
entrypoint: uvicorn app.main:app --host 0.0.0.0 --port $PORT

# Basic settings for scaling to keep costs low
instance_class: F1
automatic_scaling:
  max_instances: 10
  min_instances: 1
  target_cpu_utilization: 0.6

# Environment variables for production
env_variables:
  USE_CLOUD_SQL: "true"
  INSTANCE_CONNECTION_NAME: "your-project:your-region:your-instance"
  DB_USER: "postgres"
  DB_NAME: "buildbuzz"
  ENVIRONMENT: "production"
  DEBUG: "false"

# Beta features for Cloud SQL connections
beta_settings:
  cloud_sql_instances: "your-project:your-region:your-instance"
