# Specifies the Python version
runtime: python311

# The command to start our FastAPI application
entrypoint: uvicorn app.main:app --host 0.0.0.0 --port $PORT

# Basic settings for scaling to keep costs low
instance_class: F1
automatic_scaling:
  max_instances: 1
